### ISSUE TITLE
travis build failure : error: Environment variable 'QT_VERSION' undefined

### ISSUE THREAD

**Issue by rmallah** [lirios/fluid#211]
Travis should build should normally pass 
however below error is triggered due to issues 
not related to any code change.

```
ERROR: /usr/share/qbs/imports/qbs/ModUtils/utils.js:441 Error: Process
 '/usr/bin/qdoc' finished  with exit code 1. The standard error output was:
In file included from /home/doc/config/fluid-project.qdocconf:1,
                      /home/doc/fluid.qdocconf:1:
/usr/share/doc/qt/global/macros.qdocconf:21: error: Environment variable 'QT_VERSION' 
undefined
```  

The same problem is triggered in building demo program also.
The problem seems to be specific to 5.10.1 version of Qt as 
5.10.0 did fine.

## Environment
travis build.

**Comment by rmallah** [comment]
> The same problem is triggered in building demo program also.
> The problem seems to be specific to 5.10.1 version of Qt as
> 5.10.0 did fine.

please ignore the above comment , the observation may be flawed.

**Comment by plfiorini** [comment]
No it is true, I remember it was working with 5.10.0.
Yesterday I worked a bit on switching the CI to Ubuntu 16.04. Once I have figured out the permission denied errors, we can see if a more stable operating system yields better results.

**Comment by rmallah** [comment]
Hi I am not conversant with qbs , i build demo program using script  `run-fluiddemo.sh`
```
$  cat ../run-fluiddemo.sh 
#!/bin/bash
git submodule update --init --recursive
qbs setup-toolchains --type gcc /usr/bin/g++ gcc
qbs setup-qt   /mnt/khajana/Qt/Qt5.10.1/5.10.1/gcc_64/bin/qmake qt5 
qbs config profiles.qt5.baseProfile gcc
qbs -d build profile:qt5
qbs run --no-build -d build --products fluid-demo
```
can you please tell the qbs command equivalent to  `make clean` in the
current environment.

**Comment by plfiorini** [comment]
@rmallah It should be:

```sh
qbs clean -d build profile:qt5
```

You could also `rm -rf build` and run the following again:

```sh
qbs -d build profile:qt5
qbs run --no-build -d build --products fluid-demo
```

**Comment by rmallah** [comment]
Thanks @plfiorini for the commands   
i could create PR#214  and it seems to be fixing it.

**Comment by plfiorini** [comment]
Yeah but I wonder why qbs doesn't set the version anymore.
